substitutions:
  _BRANCH_NAME: 'feature/cloudbuild'

steps:
  # 1. Exibir o nome da branch
  - id: 'branch name'
    name: 'alpine'
    args:
    - sh
    - '-c'
    - |
        echo "Branch name is: $BRANCH_NAME"

  # 2. Verificar e mover os arquivos necessários
  - id: 'prepare files'
    name: 'alpine'
    args:
    - sh
    - '-c'
    - |
        echo "Preparando os arquivos Terraform..."
        if [ ! -f main.tf ]; then
          echo "Arquivo main.tf não encontrado! Verifique a configuração."
          exit 1
        fi
        if [ ! -f secret-key.json ]; then
          echo "Arquivo secret-key.json não encontrado! Verifique a configuração."
          exit 1
        fi

  # 3. Inicializar o Terraform
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    args:
    - 'init'

  # 4. Executar o Terraform plan
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    args:
    - 'plan'

  # 5. Aplicar mudanças no Terraform
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    args:
    - 'apply'
    - '--auto-approve'

  # 6. Fazer commit e merge automático
  - id: 'auto-merge'
    name: 'alpine/git'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        if [[ "$BRANCH_NAME" == "feature/cloudbuild" ]]; then
          echo "Branch is 'feature/cloudbuild', proceeding with auto-merge."
          git config --global user.email "henriquealcalde@hotmail.com"
          git config --global user.name "Henrique"
          git checkout develop
          git merge "$BRANCH_NAME" --no-ff -m "Auto-merge from $BRANCH_NAME to develop"
          git push origin develop
          git pull
          echo "Success"
          echo "All commands were executed, auto-merge was done."
        else
          echo "Branch is not 'feature/cloudbuild', skipping auto-merge."
        fi

options:
  logging: CLOUD_LOGGING_ONLY