steps:
  # Passo 1: Clonar o repositório
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Clonando o repositório..."
        git clone https://github.com/GabrielPerosa/Pipeline-Dataform.git || { echo "Falha ao clonar o repositório"; exit 1; }
        cd Pipeline-Dataform
        git fetch origin  # Faz o fetch para garantir que todas as branches sejam baixadas
        git checkout workspace-dataform-teste || { echo "Falha ao fazer checkout na branch workspace-dataform-teste"; exit 1; }

  # Passo 2: Instalar dependências do SQLFluff
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Instalando dependências do SQLFluff..."
        pip install --no-cache-dir sqlfluff

  # Passo 3: Verificar qualidade dos scripts SQL
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verificando qualidade dos arquivos SQL..."
        sqlfluff lint definitions/ > lint-results.txt
        if grep -q "L:  " lint-results.txt; then
          echo "Testes SQL falharam. Verifique os erros em lint-results.txt."
          exit 1
        else
          echo "Testes SQL passaram."
        fi

  # Passo 4: Recuperar credenciais do Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Recuperando credenciais do Secret Manager..."
        gcloud secrets versions access latest --secret=dataform-credentials > /workspace/.df-credentials.json
        echo "Credenciais salvas em /workspace/.df-credentials.json"
      
  # Passo 5: Verificar se o arquivo de credenciais foi recuperado
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verificando se o arquivo de credenciais foi recuperado..."
        if [ -f "/workspace/.df-credentials.json" ]; then
          echo "Arquivo de credenciais encontrado."
        else
          echo "Erro: Arquivo de credenciais não encontrado."
          exit 1
        fi

    # Passo 6: Instalar Node.js, npm, Dataform e executar
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Instalando Node.js e npm..."
        curl -sL https://deb.nodesource.com/setup_16.x | bash -
        apt-get install -y nodejs

        echo "Instalando as dependências do Dataform..."
        npm install || { echo "Falha ao instalar as dependências"; exit 1; }

        echo "Autenticando com as credenciais..."
        gcloud auth activate-service-account --key-file=/workspace/.df-credentials.json || { echo "Falha ao autenticar"; exit 1; }

        echo "Compilando o projeto Dataform..."
        dataform compile || { echo "Erro durante a compilação"; exit 1; }

        echo "Executando o Dataform..."
        dataform run || { echo "Erro ao executar o Dataform"; exit 1; }

        echo "Pipeline concluído com sucesso."


substitutions:
  _AUTHOR_EMAIL: 'gabrielperosa493@gmail.com'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
