steps:
# Passo 1: Clonar o reposit칩rio (caso necess치rio)
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/<seu-usu치rio>/<seu-reposit칩rio>.git']

# Passo 2: Rodar testes de qualidade
- name: 'gcr.io/cloud-builders/maven'
  args: ['clean', 'install']

# Passo 3: Condicional para lidar com sucesso ou falha
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'main']
  entrypoint: '/bin/bash'
  script: |
    if [ $? -ne 0 ]; then
      echo "Build falhou. Notificando falha."
      exit 1
    else
      git merge develop
      git push origin main
    fi
