substitutions:
  _BRANCH_NAME: 'feature/cloudbuild'

steps:
  # 1. Exibir o nome da branch
  - id: 'branch name'
    name: 'alpine'
    args:
    - sh
    - '-c'
    - |
        echo "Branch name is: $BRANCH_NAME"

  # 2. Configurar o Git no ambiente do Cloud Build
  - id: 'git config'
    name: 'alpine/git'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo "Configurando credenciais Git..."
        git config --global user.email "henriquealcalde@hotmail.com"
        git config --global user.name "Henrique"

  # 3. Clonar o repositório
  - id: 'clone repo'
    name: 'alpine/git'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        echo "Clonando o repositório..."
        git clone https://github.com/GabrielPerosa/Pipeline-Dataform
        cd .\Pipeline-Dataform\

  # 4. Fazer merge da branch feature/cloudbuild na develop
  - id: 'merge branch'
    name: 'alpine/git'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        cd nome-do-repositorio
        echo "Fazendo checkout da branch develop..."
        git checkout develop
        echo "Fazendo merge da branch feature/cloudbuild na develop..."
        git merge feature/cloudbuild --no-ff -m "Merge automático do Cloud Build"
        echo "Push das mudanças para a branch develop..."
        git push origin develop

  # 5. Confirmar atualização no Dataform
  - id: 'dataform update'
    name: 'alpine'
    args:
    - sh
    - '-c'
    - |
        echo "Atualizando Dataform no GCP..."
        # Verifique se há comandos necessários para forçar a atualização no Dataform (opcional)
        echo "Dataform atualizado com sucesso."

options:
  logging: CLOUD_LOGGING_ONLY