steps:
# Passo 1: Rodar testes de qualidade com Maven
- name: 'gcr.io/cloud-builders/maven'
  args: ['clean', 'install']
  id: 'Testes de Qualidade'

# Passo 2: Verificar se os testes passaram
- name: 'ubuntu'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      if [ $? -ne 0 ]; then
        echo "Build falhou. Notificando falha."
        exit 1
      fi

# Passo 3: Fazer merge para main (caso testes passem)
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch', 'origin', 'main']
  id: 'Atualizar branch main'
- name: 'gcr.io/cloud-builders/git'
  args: ['merge', 'develop']
  id: 'Merge para main'
- name: 'gcr.io/cloud-builders/git'
  args: ['push', 'origin', 'main']
  id: 'Enviar mudanças para main'
