steps:
  # Passo 2: Rodar os testes SQLFluff
  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install sqlfluff
        sqlfluff lint .

  # Passo 3: Mesclar com outra branch do GitHub
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'config --global user.name cloud-build'

      - 'config --global user.email cloud-build@google.com'

      - 'fetch'

      - 'checkout staging'
      - 'merge'
      - 'origin production'

  # Passo 4: Sincronizar com o repositório do Dataform, usando o Secret Manager
  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        - 'cd dataform/'
        - 'pip install -r requirements.txt'
        - 'python dataform.py'
        - 'print("Sucesso!")'

options:
  logging: CLOUD_LOGGING_ONLY  # Especifica que os logs serão enviados para o Cloud Logging
        

