steps:
  # Passo 1: Instalar as dependências necessárias
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Passo 2: Rodar os testes SQLFluff
  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install sqlfluff
        sqlfluff lint .

  # Passo 3: Mesclar com outra branch do GitHub
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'config'
      - '--global'
      - 'user.name'
      - 'cloud-build'

  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'config'
      - '--global'
      - 'user.email'
      - 'cloud-build@google.com'

  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'fetch'

  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'checkout'
      - 'staging'

  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'merge'
      - 'production'

  # Passo 4: Sincronizar com o repositório do Dataform, usando o Secret Manager
  - name: 'python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd dataform/ && pip install -r requirements.txt

        python dataform.py

        print("Sucesso!")
