steps:
  # Passo 1: Rodar os testes SQLFluff e Enviar para Dataform
  - name: 'python:3.12'
    id: 'Usando Python para validar SQL e enviar para o dataform'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install sqlfluff
        sqlfluff lint .

        # Roda o dataform.py
        cd dataform/
        pip install -r requirements.txt
        python dataform.py

options:
  logging: CLOUD_LOGGING_ONLY  # Especifica que os logs serão enviados para o Cloud Logging