defaultProject: terraform-438819
defaultLocation: southamerica-east1
defaultDataset: dataform_dataset
defaultAssertionDataset: dataform_dataset_assertions
dataformCoreVersion: 3.0.8

# Definindo as configurações adicionais para evitar erros
assertions:
  enabled: true
  dataset: dataform_assertions

# Configurações de opções
options:
  logging: CLOUD_LOGGING_ONLY
  timeout: '1200s'
