steps:
  # 1. Load environment variables (if needed)
  - id: 'load env'
    name: 'google/cloud-sdk'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Carregando variáveis"

  # 2. Configure Git
  - id: 'git config'
    name: 'alpine/git'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Configurando credenciais do Git..."
        git config --global user.name "$_GIT_USER_NAME"
        git config --global user.email "$_GIT_USER_EMAIL"

  # 3. Clone repository
  - id: 'clone repo'
    name: 'alpine/git'
    entrypoint: 'sh'
    secretEnv:
      - GIT_TOKEN
    args:
      - '-c'
      - |
        echo "Clonando o repositório..."
        if ! git clone https://${_GIT_USER_NAME}:${GIT_TOKEN}@github.com/seu_usuario/seu_repositorio.git; then
          echo "Falha ao clonar o repositório."
          exit 1
        fi

  # 4. Check for new commits
  - id: 'check commits'
    name: 'alpine/git'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd Pipeline-Dataform
        echo "Verificando novos commits na branch $_FEATURE_NAME..."
        git checkout $_FEATURE_NAME
        git pull origin $_FEATURE_NAME
        if [ "$(git log origin/$_BRANCH_NAME..HEAD --oneline)" = "" ]; then
          echo "Nenhum novo commit encontrado na branch $_FEATURE_NAME. Finalizando o pipeline."
          exit 0
        fi
        echo "Novos commits encontrados na branch $_FEATURE_NAME."

  # 5. Merge branches
  - id: 'merge branch'
    name: 'alpine/git'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd Pipeline-Dataform
        echo "Fazendo checkout da branch $_FEATURE_NAME..."
        git checkout $_FEATURE_NAME
        git pull
        echo "Fazendo merge da branch $_FEATURE_NAME na $_BRANCH_NAME..."
        git checkout $_BRANCH_NAME
        git pull
        git merge $_FEATURE_NAME
        echo "Push das mudanças para a branch $_BRANCH_NAME..."
        git push

  # 6. Update Dataform
  - id: 'dataform update'
    name: 'gcr.io/your-project-id/dataform-cli'  # Custom image with Dataform CLI
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Atualizando Dataform no GCP..."
        dataform run --project-dir /workspace/Pipeline-Dataform
        echo "Dataform atualizado com sucesso."
        echo "Tudo pronto."

# Substitutions
substitutions:
  _BRANCH_NAME: 'feature/testes'
  _FEATURE_NAME: 'feature/testes-base'
  _GIT_USER_NAME: 'GabrielPerosa'
  _GIT_USER_EMAIL: 'gabrielperosa493@gmail.com'

# Secrets
secrets:
  - secretEnv:
      GIT_TOKEN: projects/integracaohomologado/secrets/token-git/versions/latest

options:
  logging: CLOUD_LOGGING_ONLY